### ISSUE TITLE
Dynamically create navbar using list in `_config.yaml`

### ISSUE THREAD

**Issue by eamonburns** [btc-raspberrypiclub/cleaner-blog-jekyll#3]
Currently, the links in the navbar are hard coded. They could be created dynamically from a variable in `_config.yaml`:

```yaml
navigation:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Posts
    link: /posts/
  - name: Contact
    link: /contact/
```

This would allow for much easier extension of the basic structure, without needing to create a custom navbar layout
