### ISSUE TITLE
Improve 404 page

### ISSUE THREAD

**Issue by eamonburns** [btc-raspberrypiclub/cleaner-blog-jekyll#5]
If the 404 page has following frontmatter:
```yaml
layout: page
title: 404
description: Page not found
background: /path/to/image.jpg
permalink: /404.html
```

It will look something like this (assuming the background image is of a raspberry):
![image](https://github.com/btc-raspberrypiclub/cleaner-blog-jekyll/assets/116777388/17cb1d14-58e8-4a05-b0b3-fda25785486e)

I think this would work as a default 404 page
